In [ ]:
#Data.csv

**Step 1: Importing the libraries**

In [77]:
import pandas as pd
import numpy as np

**Step 2: Importing dataset**

In [78]:
df = pd.read_csv('Data.csv')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

**Step 3: Handling the missing data**

In [79]:
df['Salary'].fillna(df['Salary'].mean(), inplace = True)
df['Salary'] = df['Salary'].astype(int)
df['Age'].fillna(df['Age'].mean(), inplace = True)
df['Age'] = df['Age'].astype(int)

In [80]:
df

Country  Age  Salary Purchased
0   France   44   72000        No
1    Spain   27   48000       Yes
2  Germany   30   54000        No
3    Spain   38   61000        No
4  Germany   40   63777       Yes
5   France   35   58000       Yes
6    Spain   38   52000        No
7   France   48   79000       Yes
8  Germany   50   83000        No
9   France   37   67000       Yes

**Step 4: Encoding categorical data**

In [81]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
le = LabelEncoder()
df['Purchased'] = le.fit_transform(df['Purchased'])
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
df = np.array(ct.fit_transform(df))

In [82]:
print(df)

[[1.0000e+00 0.0000e+00 0.0000e+00 4.4000e+01 7.2000e+04 0.0000e+00]
 [0.0000e+00 0.0000e+00 1.0000e+00 2.7000e+01 4.8000e+04 1.0000e+00]
 [0.0000e+00 1.0000e+00 0.0000e+00 3.0000e+01 5.4000e+04 0.0000e+00]
 [0.0000e+00 0.0000e+00 1.0000e+00 3.8000e+01 6.1000e+04 0.0000e+00]
 [0.0000e+00 1.0000e+00 0.0000e+00 4.0000e+01 6.3777e+04 1.0000e+00]
 [1.0000e+00 0.0000e+00 0.0000e+00 3.5000e+01 5.8000e+04 1.0000e+00]
 [0.0000e+00 0.0000e+00 1.0000e+00 3.8000e+01 5.2000e+04 0.0000e+00]
 [1.0000e+00 0.0000e+00 0.0000e+00 4.8000e+01 7.9000e+04 1.0000e+00]
 [0.0000e+00 1.0000e+00 0.0000e+00 5.0000e+01 8.3000e+04 0.0000e+00]
 [1.0000e+00 0.0000e+00 0.0000e+00 3.7000e+01 6.7000e+04 1.0000e+00]]


**Step 5: Creating a dummy variable**

In [84]:
dv = pd.DataFrame(df)
dv

0    1    2     3        4    5
0  1.0  0.0  0.0  44.0  72000.0  0.0
1  0.0  0.0  1.0  27.0  48000.0  1.0
2  0.0  1.0  0.0  30.0  54000.0  0.0
3  0.0  0.0  1.0  38.0  61000.0  0.0
4  0.0  1.0  0.0  40.0  63777.0  1.0
5  1.0  0.0  0.0  35.0  58000.0  1.0
6  0.0  0.0  1.0  38.0  52000.0  0.0
7  1.0  0.0  0.0  48.0  79000.0  1.0
8  0.0  1.0  0.0  50.0  83000.0  0.0
9  1.0  0.0  0.0  37.0  67000.0  1.0

**Step 6: Splitting the datasets into training sets and Test sets**

In [85]:
from sklearn.model_selection import train_test_split
df_train, df_test = train_test_split(df, test_size = 0.2, random_state = 1)

In [86]:
df_train

array([[0.0000e+00, 0.0000e+00, 1.0000e+00, 3.8000e+01, 5.2000e+04,
        0.0000e+00],
       [0.0000e+00, 1.0000e+00, 0.0000e+00, 4.0000e+01, 6.3777e+04,
        1.0000e+00],
       [1.0000e+00, 0.0000e+00, 0.0000e+00, 4.4000e+01, 7.2000e+04,
        0.0000e+00],
       [0.0000e+00, 0.0000e+00, 1.0000e+00, 3.8000e+01, 6.1000e+04,
        0.0000e+00],
       [0.0000e+00, 0.0000e+00, 1.0000e+00, 2.7000e+01, 4.8000e+04,
        1.0000e+00],
       [1.0000e+00, 0.0000e+00, 0.0000e+00, 4.8000e+01, 7.9000e+04,
        1.0000e+00],
       [0.0000e+00, 1.0000e+00, 0.0000e+00, 5.0000e+01, 8.3000e+04,
        0.0000e+00],
       [1.0000e+00, 0.0000e+00, 0.0000e+00, 3.5000e+01, 5.8000e+04,
        1.0000e+00]])

In [87]:
df_test 

array([[0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04, 0.0e+00],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.7e+01, 6.7e+04, 1.0e+00]])

**Step 7: Feature Scaling**

In [89]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
df_train = sc.fit_transform(df_train)
df_test = sc.transform(df_test)

In [92]:
print(df_train)

[[-0.77459667 -0.57735027  1.29099445 -0.28942984 -1.07811699 -1.        ]
 [-0.77459667  1.73205081 -0.77459667  0.         -0.07018988  1.        ]
 [ 1.29099445 -0.57735027 -0.77459667  0.57885968  0.63357038 -1.        ]
 [-0.77459667 -0.57735027  1.29099445 -0.28942984 -0.30785767 -1.        ]
 [-0.77459667 -0.57735027  1.29099445 -1.88129397 -1.42045447  1.        ]
 [ 1.29099445 -0.57735027 -0.77459667  1.15771937  1.23266096  1.        ]
 [-0.77459667  1.73205081 -0.77459667  1.44714921  1.57499844 -1.        ]
 [ 1.29099445 -0.57735027 -0.77459667 -0.72357461 -0.56461078  1.        ]]


In [93]:
print(df_test)

[[-0.77459667  1.73205081 -0.77459667 -1.44714921 -0.90694825 -1.        ]
 [ 1.29099445 -0.57735027 -0.77459667 -0.43414476  0.20564854  1.        ]]
